### ISSUE TITLE
Cycle materials convertr

### ISSUE THREAD

**Issue by johnzero7** [johnzero7/xps_tools#2]
TODO cycles material converter

**Comment by Brachi** [comment]
I have an old code for creating a generic node setup for Diffuse, specular, glow, etc. Did you already started coding this?

**Comment by johnzero7** [comment]
the conveter I made is almost complete. 
It makes really simple generic Cycles material, so there is a lot room for improvement.
If you still want to share your code it might help me a lot.

**Comment by Fighter19** [comment]
Is the cycles converter actually packed with the newest release of the plugin? (1.5.2) Because I tried to import a model with Blender 2.74 in cycles but it resulted in being completely untextured.

**Comment by johnzero7** [comment]
Yes, it is.
There are 3 new button on the XPS toolshelf to alternate the materials between BI and Cycles.
On import the addon always create BI material. After that you have the option to generate Cycles materials for all the meshes or only the selected ones. The third button changes the engine back to Internal materials and disables the Nodes.

**Comment by Fighter19** [comment]
Thank you!
