### ISSUE TITLE
Textures are not imported on Linux (presumably also on Mac)

### ISSUE THREAD

**Issue by CarlosEduardoNovaes** [johnzero7/xps_tools#6]
Good job, congratulations.

One small problem I ran into was that on Linux the texture filenames are not imported correctly (presumably also on mac). I did some small changes on the read_xxx_xps.py files, so they always use ntpath.basename. This should work since XNALara is for windows only. maybe some equivalent correction should be made to the exporter, but for a quick hack I am done. Importing of XNALara files on my Linux box now works like a charm. Thank you for this excellent work.

I would like to send you this modification, so you can made the appropriate changes if you wish (maybe a high grade importer could be  included in the official blender release).

Sadly the diff code is not printed correctly. basically I did:

On both read_ascii_xps.py and read_bin_xps.py
    Add a import ntpath

On read_ascii_xps.py
    Change line
        textureFile = os.path.basename(ascii_ops.readString(file))
    to
        textureFile = ntpath.basename(ascii_ops.readString(file))

On read_bin_xps.py
    Change line 
       textureFile = os.path.basename(readFilesString(file))
    to
       textureFile = ntpath.basename(readFilesString(file))

**Comment by johnzero7** [comment]
Sorry for the delay and thanks a lot for your contribution!
